version: '3.8'

services:
  ocr-api:
    build:
      context: ..                 # 回到项目根目录
      dockerfile: docker/Dockerfile
    container_name: ocr-api
    ports:
      - "8000:8000"
    volumes:
      - ../models:/app/models          # 挂载模型目录（宿主机 models/ 映射到容器 /app/models）
      - ../api:/app/api                # 挂载代码目录，方便热更新（可选）
    environment:
      - PADDLE_HOME=/app/models
      - FLAGS_use_mkldnn=0
    restart: unless-stopped

